### ISSUE TITLE
impossible to download the source from the website

### ISSUE THREAD

**Issue by szbnwer** [MaqaoTeam/MAQAO#1]
hi there! :)

firefox cant even add ur selfsigned cert as an exception here:
https://git.maqao.org/MAQAO/MAQAO

u could use letsencrypt or cloudflare instead of the self signed cert.

all the bests for u! :)

**Comment by MaqaoTeam** [comment]
Hi, thanks a lot for your advice. We forwarded it to the admins of the website who made the necessary adjustments. You should be able to access the repository without warning now.

Best regards,
The MAQAO dev team.
