### ISSUE TITLE
Dependencie missed

### ISSUE THREAD

**Issue by Matth37** [MaqaoTeam/MAQAO#2]
Hi I needed to install the libunwind-dev package for Ubuntu 21.04.

I think you can add this in the list.

ps: url link for the documentation doesn't work too

**Comment by MaqaoTeam** [comment]
Thanks for your contribution, sadly this repository is not maintained and is out of date.
We are currently working on a new version for the Arm architectures. We hope to release it in the next months.
If you are not targeting Arm architectures then you can find latest releases here: https://maqao.exascale-computing.eu/index.html

**Comment by Matth37** [comment]
Thanks for your quick reply. In fact this link is very useful.
